version: '3.8'

services:
  redis-local-server:
    image: redis:latest
    container_name: redis-local-server
    platform: linux/amd64
    environment:
      - REDIS_PASSWORD=admin
    command: redis-server --requirepass admin
    ports:
      - "6381:6379"
      
  evv-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: evv-service
    restart: on-failure
    depends_on:
      - redis-local-server
      - postgresql
    ports:
      - "3200:3200"
    volumes:
      - ./.env:/app/.env